{% set name = "mpl-sphinx-theme" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpl_sphinx_theme-{{ version }}.tar.gz
  sha256: a78c49ca43f7cb0f57cace6ca62bf3af23968ad4cf7beebe2b1721dea5d36285

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - pydata-sphinx-theme >=0.10.0
    - python >=3.6

test:
  imports:
    - mpl_sphinx_theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/matplotlib/mpl-sphinx-theme
  summary: Matplotlib theme for Sphinx
  license: LicenseRef-PSF-based
  license_family: PSF
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - awvwgk
