{% set name = "mpl-sphinx-theme" %}
{% set version = "3.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpl_sphinx_theme-{{ version }}.tar.gz
  sha256: 0b3c6d04f2090c1f60c4dd8efb92a6a17398ff865d88336ec6e797553eb867cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - pydata-sphinx-theme >=0.10.0
    - python >={{ python_min }}

test:
  imports:
    - mpl_sphinx_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/matplotlib/mpl-sphinx-theme
  summary: Matplotlib theme for Sphinx
  license: LicenseRef-PSF-based
  license_family: PSF
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - awvwgk
