{% set name = "mpl-sphinx-theme" %}
{% set version = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpl_sphinx_theme-{{ version }}.tar.gz
  sha256: d9ebd53bbb44ae89a84bd6e6aa747cc725fb293f56d7ce061c9603521b6f21b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - pydata-sphinx-theme >=0.10.0
    - python >={{ python_min }}

test:
  imports:
    - mpl_sphinx_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/matplotlib/mpl-sphinx-theme
  summary: Matplotlib theme for Sphinx
  license: LicenseRef-PSF-based
  license_family: PSF
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - awvwgk
